### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by alonl** [shaunxu/angular-jsoneditor#1]
Hi,
Is there a change you can give an example of how to use it?
Thanks,

**Comment by shaunxu** [comment]
Yes please have a look https://gist.github.com/shaunxu/a8508bfd12a6826a820d

**Comment by alonl** [comment]
Thanks a lot!
I'd suggest to put it on the README...
:)

**Comment by shaunxu** [comment]
Thanks and good to see you like to. Definitely should be in readme.md but I'm busy with my new son recently :) Will update soon hopefully.
